### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [m-delarosa/mod_0_skills#1]
Hey Mike, nice work on the assessment. You are officially `technical ready`. For the most part, great job with your naming conventions - it was really clear to me what each attribute or method did. Also, good job using the correct syntax on your data types. 

One thing to keep in mind moving forward: `isOn` would likely be a better name than `ovenOn` since we know that it applies to an instance of an oven.

**Comment by m-delarosa** [comment]
Thanks @damwhit, I really appreciate the feedback. Using `isOn` does make more sense. Please let me know if there is anything else you think I can work on.
